### Import the numpy package

In [3]:
import numpy as np 

### Generate a 1D NumPy array of 10 random integers between 1 and 100.

In [2]:
array_1d = np.random.randint(1, 101, size=10)
print(array_1d)  

[77 48 22 28  2 65  1 98 96 56]


### Access and print the first and last elements of the array.

In [4]:
first_element = array_1d[0]  
last_element = array_1d[-1]  

print("First element:", first_element)
print("Last element:", last_element)


First element: 77
Last element: 56


### Generate a 2D NumPy array of shape (3, 3) with random floating-point numbers.

In [6]:
array_2d = np.random.rand(3, 3)
print(array_2d)


[[0.03926385 0.22879919 0.11348162]
 [0.47854255 0.37187339 0.40693735]
 [0.89072337 0.10354513 0.50421213]]


### Print the first row of the 2D array.

In [7]:
print(array_2d[0])


[0.03926385 0.22879919 0.11348162]


### Print the last column of the 2D array.

In [8]:
print(array_2d[:, -1])


[0.11348162 0.40693735 0.50421213]


### Print a sub-array consisting of the first two rows and first two columns.

In [9]:
sub_array = array_2d[:2, :2]
print(sub_array)


[[0.03926385 0.22879919]
 [0.47854255 0.37187339]]


### Generate two 1D arrays of 5 random integers each, in the range [0, 10)


In [17]:
array1 = np.random.randint(0, 10, 5)
array2 = np.random.randint(0, 10, 5)

print(array1)
print(array2)

[9 2 7 2 5]
[4 2 5 5 2]


### Add the two arrays and print the result

In [18]:
added_arrays = array1 + array2
print("Added Arrays:", added_arrays)


Added Arrays: [13  4 12  7  7]


### Multiply the two arrays (element-wise) and print the result


In [19]:
multiplied_arrays = array1 * array2
print("Multiplied Arrays:", multiplied_arrays)


Multiplied Arrays: [36  4 35 10 10]


### Calculate the square of every element in the first array and print it


In [20]:
squared_array1 = array1 ** 2
print("Squared Array 1:", squared_array1)

Squared Array 1: [81  4 49  4 25]


### Generate two 2D NumPy arrays, A of shape (2, 3) and B of shape (3, 2), with random integers.

In [21]:
A = np.random.randint(0, 10, (2, 3))
B = np.random.randint(0, 10, (3, 2))

print("Array A:")
print(A)
print("Array B:")
print(B)

Array A:
[[4 2 8]
 [3 1 4]]
Array B:
[[5 2]
 [7 6]
 [1 3]]


### Perform matrix multiplication between A and B and print the result

In [22]:
result_matrix_multiplication = A @ B
print("Matrix multiplication result (A @ B):")
print(result_matrix_multiplication)

Matrix multiplication result (A @ B):
[[42 44]
 [26 24]]


### Can A and B perform element-wise multiplication using *

No, A and B cannot perform element-wise multiplication because their shapes do not match. Element-wise multiplication requires the arrays to have the same shape, but A is (2, 3) and B is (3, 2).